table Customer
	lineageTag: 22c8b740-d9e2-4fff-a998-2f511ef33e94

	column CustomerID
		dataType: int64
		formatString: 0
		lineageTag: 7382ab10-f97d-4ec5-a126-3be7439ab3f2
		summarizeBy: none
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column CustomerName
		dataType: string
		lineageTag: 1d8d1d82-674d-4ad6-afab-8a071722d56e
		summarizeBy: none
		sourceColumn: CustomerName

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 851e48cb-f8c8-4938-bd93-b7fb22d836ba
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	partition Customer = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\BurelaSuryaPrathap\Downloads\OrderDetails_Data\OrderDetails_Data\Customer.csv"),[Delimiter=",", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"CustomerID", Int64.Type}, {"CustomerName", type text}, {"Segment", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

