table Sales
	lineageTag: 789cbda5-55df-4571-91c3-ce1549dbe600

	measure AOV = ```
			DIVIDE(SUM(Sales[SalesAmount]), COUNT(Sales[OrderID]))
			
			```
		lineageTag: b02d0404-5189-430f-b6d4-8d35cb6f92ec

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column OrderID
		dataType: int64
		formatString: 0
		lineageTag: df0b8ad3-c391-4bbb-ade7-4e2ab1cb6f61
		summarizeBy: count
		sourceColumn: OrderID

		annotation SummarizationSetBy = Automatic

	column DateKey
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1f3cb716-21b0-4d77-b4d0-03a754930650
		summarizeBy: none
		sourceColumn: DateKey

		variation Variation
			isDefault
			relationship: 2cf212f0-7e08-486d-beab-4ab47ea5eb6e
			defaultHierarchy: LocalDateTable_d1b0c5d6-5b9e-4403-83fc-3ed31cddaec6.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column CustomerID
		dataType: int64
		formatString: 0
		lineageTag: 1905df09-f0cd-4b9d-9ad5-b0530049bca9
		summarizeBy: none
		sourceColumn: CustomerID

		annotation SummarizationSetBy = Automatic

	column ProductID
		dataType: int64
		formatString: 0
		lineageTag: cbe71202-6746-4e64-8c68-2fb942aa8533
		summarizeBy: none
		sourceColumn: ProductID

		annotation SummarizationSetBy = Automatic

	column RegionID
		dataType: int64
		formatString: 0
		lineageTag: ebd92042-ec73-4810-960f-704a09ae86e5
		summarizeBy: none
		sourceColumn: RegionID

		annotation SummarizationSetBy = Automatic

	column SalesRepID
		dataType: int64
		formatString: 0
		lineageTag: c82eada3-7fe1-4b02-a2f8-443f30aeebe0
		summarizeBy: none
		sourceColumn: SalesRepID

		annotation SummarizationSetBy = Automatic

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 692f62eb-bee3-4c10-a804-dfd117ddb967
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column SalesAmount
		dataType: int64
		formatString: 0
		lineageTag: 17315c38-7c25-4033-890d-728cf1985b54
		summarizeBy: sum
		sourceColumn: SalesAmount

		annotation SummarizationSetBy = Automatic

	partition Sales = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\BurelaSuryaPrathap\Downloads\OrderDetails_Data\OrderDetails_Data\Sales.csv"),[Delimiter=",", Columns=8, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"OrderID", Int64.Type}, {"DateKey", type date}, {"CustomerID", Int64.Type}, {"ProductID", Int64.Type}, {"RegionID", Int64.Type}, {"SalesRepID", Int64.Type}, {"Quantity", Int64.Type}, {"SalesAmount", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

